name: Build Standalone WASM and Release
 
on:
  push:
    tags:
      - 'v*'
    branches: [ 'b*' ]
  workflow_dispatch:
 
jobs:
  build-wasm:
    runs-on: ubuntu-22.04
    env:
      EMSCRIPTEN_VERSION: 3.1.61
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Emscripten
      run: ./scripts/install-ci-linux.sh
    
    - name: Build standalone WASM
      run: |
        echo '==> start source emsdk_env'
        source ./emscripten/emsdk/emsdk_env.sh
        echo '==> start build'
        STANDALONE=1 bash -x ./build-emscripten.sh .
        ls -lh
    
