name: Build Standalone WASM and Release
 
on:
  push:
    tags:
      - 'v*'
    # branches: [ 'b*' ]
  workflow_dispatch:
 
jobs:
  build-wasm:
    runs-on: ubuntu-22.04
    env:
      EMSCRIPTEN_VERSION: 3.1.61
      
    steps:
    - uses: actions/checkout@v4

    - name: Prepare build variables
      id: prep
      run: |
        # 提取版本号
        VERSION=${GITHUB_REF_NAME}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    
    - name: Install Emscripten
      run: ./scripts/install-ci-linux.sh
    
    - name: Build standalone WASM
      run: |
        echo '==> start source emsdk_env'
        source ./emscripten/emsdk/emsdk_env.sh
        echo '==> start build'
        STANDALONE=1 bash -x ./build-emscripten.sh .
        ls -lh
        mkdir -p build
        cp libheif.wasm build/libheif-${{ env.VERSION }}-standalone.wasm

    - name: upload-artifact-standalone
      uses: actions/upload-artifact@v4
      with:
        name: libheif-${{ env.VERSION }}-standalone-wasm
        path: build/libheif-${{ env.VERSION }}-standalone.wasm

    - name: Build Js WASM
      run: |
        source ./emscripten/emsdk/emsdk_env.sh
        STANDALONE=0 USE_TYPESCRIPT=0 bash -x ./build-emscripten.sh .
        ls -lh
        mkdir -p build
        cp libheif.wasm build/libheif-${{ env.VERSION }}-js.wasm
        cp libheif.js build/libheif-${{ env.VERSION }}.js

    - name: upload-artifact-js
      uses: actions/upload-artifact@v4
      with:
        name: libheif-${{ env.VERSION }}-js-wasm
        path: |
          build/libheif-${{ env.VERSION }}-js.wasm
          build/libheif-${{ env.VERSION }}.js